from sqlalchemy.orm import Session
from app.db.database import SessionLocal, engine
from app.db.models import ExercisePlan, Base

# Create tables if not exist
Base.metadata.create_all(bind=engine)

SEED_EXERCISES = [
    # --- [HOME] STRENGTH / REP-BASED (12 items) ---
    {"plan_id": "home_squat_standard", "name": "맨몸 스쿼트", "location": "home", "type": "rep-based", "required_equipment": "", "target_parts": "legs,glutes", "avoid_if_pain": "knee", "intensity": "medium", "minutes": 10, "sets": 3, "reps": 15, "target_rpe": 6, "rest_seconds": 60, "met_value": 5.0, "video_url": "https://www.youtube.com/results?search_query=맨몸+스쿼트+자세"},
    {"plan_id": "home_pushup_standard", "name": "푸쉬업", "location": "home", "type": "rep-based", "required_equipment": "", "target_parts": "chest,arms,shoulder", "avoid_if_pain": "wrist,shoulder", "intensity": "medium", "minutes": 10, "sets": 3, "reps": 12, "target_rpe": 7, "rest_seconds": 90, "met_value": 8.0, "video_url": "https://www.youtube.com/results?search_query=푸쉬업+정석"},
    {"plan_id": "home_lunges", "name": "워킹 런지", "location": "home", "type": "rep-based", "required_equipment": "", "target_parts": "legs,glutes", "avoid_if_pain": "knee,ankle", "intensity": "high", "minutes": 12, "sets": 3, "reps": 20, "target_rpe": 8, "rest_seconds": 60, "met_value": 6.0, "video_url": "https://www.youtube.com/results?search_query=런지+자세"},
    {"plan_id": "home_diamond_pushup", "name": "다이아몬드 푸쉬업", "location": "home", "type": "rep-based", "required_equipment": "", "target_parts": "arms,chest", "avoid_if_pain": "wrist", "intensity": "high", "minutes": 10, "sets": 3, "reps": 8, "target_rpe": 8, "rest_seconds": 90, "met_value": 8.0, "video_url": "https://www.youtube.com/results?search_query=다이아몬드+푸쉬업+자세"},
    {"plan_id": "home_crunch", "name": "크런치", "location": "home", "type": "rep-based", "required_equipment": "", "target_parts": "core", "avoid_if_pain": "lower_back,neck", "intensity": "low", "minutes": 8, "sets": 3, "reps": 20, "target_rpe": 5, "rest_seconds": 45, "met_value": 3.0, "video_url": "https://www.youtube.com/results?search_query=크런치+자세"},
    {"plan_id": "home_leg_raise", "name": "레그 레이즈", "location": "home", "type": "rep-based", "required_equipment": "", "target_parts": "core,legs", "avoid_if_pain": "lower_back", "intensity": "medium", "minutes": 8, "sets": 3, "reps": 15, "target_rpe": 6, "rest_seconds": 60, "met_value": 3.5, "video_url": "https://www.youtube.com/results?search_query=레그레이즈+자세"},
    {"plan_id": "home_plank_updown", "name": "플랭크 업다운", "location": "home", "type": "rep-based", "required_equipment": "", "target_parts": "core,shoulder,arms", "avoid_if_pain": "wrist,shoulder", "intensity": "high", "minutes": 10, "sets": 3, "reps": 12, "target_rpe": 8, "rest_seconds": 60, "met_value": 7.0, "video_url": "https://www.youtube.com/results?search_query=플랭크+업다운"},
    {"plan_id": "home_glute_bridge", "name": "글루트 브릿지", "location": "home", "type": "rep-based", "required_equipment": "", "target_parts": "glutes,lower_back", "avoid_if_pain": "lower_back", "intensity": "low", "minutes": 10, "sets": 3, "reps": 20, "target_rpe": 4, "rest_seconds": 45, "met_value": 3.0, "video_url": "https://www.youtube.com/results?search_query=브릿지+운동+자세"},
    {"plan_id": "home_superman", "name": "슈퍼맨 홀드", "location": "home", "type": "time-based", "required_equipment": "", "target_parts": "back,glutes", "avoid_if_pain": "lower_back", "intensity": "medium", "minutes": 5, "sets": 3, "reps": 1, "target_rpe": 6, "rest_seconds": 45, "met_value": 3.0, "video_url": "https://www.youtube.com/results?search_query=슈퍼맨+운동+자세"},
    {"plan_id": "home_burpee_classic", "name": "버피 테스트", "location": "home", "type": "rep-based", "required_equipment": "", "target_parts": "full_body", "avoid_if_pain": "knee,wrist", "intensity": "high", "minutes": 15, "sets": 4, "reps": 15, "target_rpe": 9, "rest_seconds": 60, "met_value": 10.0, "video_url": "https://www.youtube.com/results?search_query=버피테스트+정석"},
    {"plan_id": "home_mountain_climber", "name": "마운틴 클라이머", "location": "home", "type": "time-based", "required_equipment": "", "target_parts": "core,cardio", "avoid_if_pain": "wrist,shoulder", "intensity": "high", "minutes": 10, "sets": 3, "reps": 1, "target_rpe": 8, "rest_seconds": 60, "met_value": 8.0, "video_url": "https://www.youtube.com/results?search_query=마운틴+클라이머+자세"},
    {"plan_id": "home_wall_sit", "name": "벽 대고 버티기 (월싯)", "location": "home", "type": "time-based", "required_equipment": "", "target_parts": "legs", "avoid_if_pain": "knee", "intensity": "medium", "minutes": 6, "sets": 3, "reps": 1, "target_rpe": 7, "rest_seconds": 60, "met_value": 4.0, "video_url": "https://www.youtube.com/results?search_query=wall+sit+exercise"},

    # --- [GYM] MACHINE / BARBELL (20 items) ---
    {"plan_id": "gym_deadlift_conv", "name": "컨벤셔널 데드리프트", "location": "gym", "type": "rep-based", "required_equipment": "barbell", "target_parts": "back,legs,core", "avoid_if_pain": "lower_back", "intensity": "high", "minutes": 25, "sets": 5, "reps": 5, "target_rpe": 9, "rest_seconds": 180, "met_value": 6.0, "video_url": "https://www.youtube.com/results?search_query=데드리프트+정석"},
    {"plan_id": "gym_bench_press_barbell", "name": "바벨 벤치프레스", "location": "gym", "type": "rep-based", "required_equipment": "barbell,bench", "target_parts": "chest,arms", "avoid_if_pain": "shoulder,wrist", "intensity": "high", "minutes": 20, "sets": 5, "reps": 8, "target_rpe": 8, "rest_seconds": 120, "met_value": 6.0, "video_url": "https://www.youtube.com/results?search_query=벤치프레스+자세"},
    {"plan_id": "gym_squat_barbell", "name": "바벨 백 스쿼트", "location": "gym", "type": "rep-based", "required_equipment": "barbell,squat_rack", "target_parts": "legs,glutes", "avoid_if_pain": "knee,lower_back", "intensity": "high", "minutes": 25, "sets": 5, "reps": 8, "target_rpe": 9, "rest_seconds": 150, "met_value": 7.0, "video_url": "https://www.youtube.com/results?search_query=바벨+스쿼트+자세"},
    {"plan_id": "gym_lat_pulldown_wide", "name": "랫풀다운 (와이드)", "location": "gym", "type": "rep-based", "required_equipment": "lat_pulldown_machine", "target_parts": "back", "avoid_if_pain": "shoulder", "intensity": "medium", "minutes": 15, "sets": 4, "reps": 12, "target_rpe": 7, "rest_seconds": 90, "met_value": 4.0, "video_url": "https://www.youtube.com/results?search_query=랫풀다운+자세"},
    {"plan_id": "gym_shoulder_press_dumbbell", "name": "덤벨 숄더 프레스", "location": "gym", "type": "rep-based", "required_equipment": "dumbbell", "target_parts": "shoulder", "avoid_if_pain": "shoulder", "intensity": "medium", "minutes": 15, "sets": 4, "reps": 10, "target_rpe": 7, "rest_seconds": 90, "met_value": 4.5, "video_url": "https://www.youtube.com/results?search_query=덤벨+숄더프레스+자세"},
    {"plan_id": "gym_leg_press_machine", "name": "레그 프레스", "location": "gym", "type": "rep-based", "required_equipment": "leg_press_machine", "target_parts": "legs", "avoid_if_pain": "knee", "intensity": "medium", "minutes": 15, "sets": 4, "reps": 12, "target_rpe": 7, "rest_seconds": 120, "met_value": 5.0, "video_url": "https://www.youtube.com/results?search_query=레그프레스+자세"},
    {"plan_id": "gym_seated_row_machine", "name": "시티드 로우", "location": "gym", "type": "rep-based", "required_equipment": "row_machine", "target_parts": "back", "avoid_if_pain": "lower_back", "intensity": "medium", "minutes": 15, "sets": 4, "reps": 12, "target_rpe": 7, "rest_seconds": 90, "met_value": 4.0, "video_url": "https://www.youtube.com/results?search_query=시티드+로우+자세"},
    {"plan_id": "gym_incline_bench_press", "name": "인클라인 벤치프레스", "location": "gym", "type": "rep-based", "required_equipment": "barbell,incline_bench", "target_parts": "chest,shoulder", "avoid_if_pain": "shoulder", "intensity": "high", "minutes": 20, "sets": 4, "reps": 8, "target_rpe": 8, "rest_seconds": 120, "met_value": 6.0, "video_url": "https://www.youtube.com/results?search_query=인클라인+벤치프레스+자세"},
    {"plan_id": "gym_leg_curl", "name": "레그 컬 (햄스트링)", "location": "gym", "type": "rep-based", "required_equipment": "leg_curl_machine", "target_parts": "legs", "avoid_if_pain": "knee", "intensity": "low", "minutes": 10, "sets": 3, "reps": 15, "target_rpe": 6, "rest_seconds": 60, "met_value": 3.5, "video_url": "https://www.youtube.com/results?search_query=레그컬+자세"},
    {"plan_id": "gym_side_lateral_raise", "name": "사이드 레터럴 레이즈", "location": "gym", "type": "rep-based", "required_equipment": "dumbbell", "target_parts": "shoulder", "avoid_if_pain": "shoulder", "intensity": "low", "minutes": 12, "sets": 4, "reps": 15, "target_rpe": 7, "rest_seconds": 60, "met_value": 3.0, "video_url": "https://www.youtube.com/results?search_query=사이드+레터럴+레이즈+자세"},
    {"plan_id": "gym_barbell_curl", "name": "바벨 컬 (이두)", "location": "gym", "type": "rep-based", "required_equipment": "barbell", "target_parts": "arms", "avoid_if_pain": "wrist", "intensity": "low", "minutes": 10, "sets": 3, "reps": 12, "target_rpe": 6, "rest_seconds": 60, "met_value": 3.0, "video_url": "https://www.youtube.com/results?search_query=바벨컬+자세"},
    {"plan_id": "gym_triceps_pushdown", "name": "케이블 푸쉬다운 (삼두)", "location": "gym", "type": "rep-based", "required_equipment": "cable_machine", "target_parts": "arms", "avoid_if_pain": "elbow", "intensity": "low", "minutes": 10, "sets": 3, "reps": 12, "target_rpe": 6, "rest_seconds": 60, "met_value": 3.0, "video_url": "https://www.youtube.com/results?search_query=케이블+푸쉬다운+자세"},
    {"plan_id": "gym_chest_fly_machine", "name": "체스트 플라이 머신", "location": "gym", "type": "rep-based", "required_equipment": "fly_machine", "target_parts": "chest", "avoid_if_pain": "shoulder", "intensity": "medium", "minutes": 12, "sets": 3, "reps": 15, "target_rpe": 7, "rest_seconds": 60, "met_value": 4.0, "video_url": "https://www.youtube.com/results?search_query=체스트플라이+자세"},
    {"plan_id": "gym_romanian_deadlift", "name": "루마니안 데드리프트", "location": "gym", "type": "rep-based", "required_equipment": "barbell", "target_parts": "back,glutes,legs", "avoid_if_pain": "lower_back", "intensity": "high", "minutes": 20, "sets": 4, "reps": 10, "target_rpe": 8, "rest_seconds": 120, "met_value": 5.5, "video_url": "https://www.youtube.com/results?search_query=루마니안+데드리프트+자세"},
    {"plan_id": "gym_pull_up", "name": "풀업 (턱걸이)", "location": "gym", "type": "rep-based", "required_equipment": "pullup_bar", "target_parts": "back,arms", "avoid_if_pain": "shoulder,elbow", "intensity": "high", "minutes": 15, "sets": 4, "reps": 8, "target_rpe": 9, "rest_seconds": 120, "met_value": 8.0, "video_url": "https://www.youtube.com/results?search_query=풀업+자세"},
    {"plan_id": "gym_dips", "name": "딥스 (삼두/가슴)", "location": "gym", "type": "rep-based", "required_equipment": "dip_station", "target_parts": "arms,chest", "avoid_if_pain": "shoulder,wrist", "intensity": "high", "minutes": 12, "sets": 3, "reps": 10, "target_rpe": 8, "rest_seconds": 90, "met_value": 7.0, "video_url": "https://www.youtube.com/results?search_query=딥스+자세"},
    {"plan_id": "gym_leg_extension", "name": "레그 익스텐션", "location": "gym", "type": "rep-based", "required_equipment": "leg_extension_machine", "target_parts": "legs", "avoid_if_pain": "knee", "intensity": "medium", "minutes": 10, "sets": 3, "reps": 15, "target_rpe": 7, "rest_seconds": 60, "met_value": 4.0, "video_url": "https://www.youtube.com/results?search_query=레그익스텐션+자세"},
    {"plan_id": "gym_treadmill_interval", "name": "트레드밀 인터벌", "location": "gym", "type": "time-based", "required_equipment": "treadmill", "target_parts": "cardio", "avoid_if_pain": "knee,ankle", "intensity": "high", "minutes": 20, "sets": 1, "reps": 1, "target_rpe": 8, "rest_seconds": 0, "met_value": 10.0, "video_url": "https://www.youtube.com/results?search_query=treadmill+interval+workout"},
    {"plan_id": "gym_stationary_bike", "name": "실내 자전거", "location": "gym", "type": "time-based", "required_equipment": "stationary_bike", "target_parts": "cardio,legs", "avoid_if_pain": "knee", "intensity": "medium", "minutes": 30, "sets": 1, "reps": 1, "target_rpe": 6, "rest_seconds": 0, "met_value": 7.0, "video_url": "https://www.youtube.com/results?search_query=stationary+bike+workout"},
    {"plan_id": "gym_elliptical", "name": "엘립티컬", "location": "gym", "type": "time-based", "required_equipment": "elliptical_machine", "target_parts": "cardio,full_body", "avoid_if_pain": "knee,ankle", "intensity": "medium", "minutes": 20, "sets": 1, "reps": 1, "target_rpe": 5, "rest_seconds": 0, "met_value": 5.0, "video_url": "https://www.youtube.com/results?search_query=elliptical+workout+tips"},

    # --- [STRETCHING / RECOVERY] (10 items) ---
    {"plan_id": "home_stretch_morning", "name": "모닝 전신 스트레칭", "location": "home", "type": "time-based", "required_equipment": "", "target_parts": "full_body", "avoid_if_pain": "", "intensity": "low", "minutes": 10, "sets": 1, "reps": 1, "target_rpe": 3, "rest_seconds": 0, "met_value": 2.5, "is_stretching": True, "video_url": "https://www.youtube.com/results?search_query=아침+스트레칭"},
    {"plan_id": "home_stretch_back", "name": "허리 통증 완화 스트레칭", "location": "home", "type": "time-based", "required_equipment": "", "target_parts": "back,core", "avoid_if_pain": "", "intensity": "low", "minutes": 10, "sets": 1, "reps": 1, "target_rpe": 3, "rest_seconds": 0, "met_value": 2.0, "is_stretching": True, "video_url": "https://www.youtube.com/results?search_query=허리+스트레칭"},
    {"plan_id": "home_stretch_neck", "name": "거북목 교정 스트레칭", "location": "home", "type": "time-based", "required_equipment": "", "target_parts": "neck,shoulder", "avoid_if_pain": "", "intensity": "low", "minutes": 5, "sets": 1, "reps": 1, "target_rpe": 2, "rest_seconds": 0, "met_value": 1.5, "is_stretching": True, "video_url": "https://www.youtube.com/results?search_query=거북목+교정+운동"},
    {"plan_id": "home_stretch_hip", "name": "골반 교정 스트레칭", "location": "home", "type": "time-based", "required_equipment": "", "target_parts": "glutes,legs", "avoid_if_pain": "hip", "intensity": "low", "minutes": 12, "sets": 1, "reps": 1, "target_rpe": 4, "rest_seconds": 0, "met_value": 2.3, "is_stretching": True, "video_url": "https://www.youtube.com/results?search_query=골반+스트레칭"},
    {"plan_id": "home_foam_roller_legs", "name": "하체 폼롤러 마사지", "location": "home", "type": "time-based", "required_equipment": "foam_roller", "target_parts": "legs,glutes", "avoid_if_pain": "", "intensity": "low", "minutes": 15, "sets": 1, "reps": 1, "target_rpe": 4, "rest_seconds": 0, "met_value": 2.5, "is_stretching": True, "video_url": "https://www.youtube.com/results?search_query=하체+폼롤러+마사지"},
    {"plan_id": "home_foam_roller_back", "name": "등/허리 폼롤러 마사지", "location": "home", "type": "time-based", "required_equipment": "foam_roller", "target_parts": "back", "avoid_if_pain": "lower_back", "intensity": "low", "minutes": 10, "sets": 1, "reps": 1, "target_rpe": 3, "rest_seconds": 0, "met_value": 2.5, "is_stretching": True, "video_url": "https://www.youtube.com/results?search_query=등+폼롤러+마사지"},
    {"plan_id": "home_yoga_basic", "name": "기초 요가 루틴", "location": "home", "type": "time-based", "required_equipment": "yoga_mat", "target_parts": "full_body,core", "avoid_if_pain": "", "intensity": "low", "minutes": 20, "sets": 1, "reps": 1, "target_rpe": 4, "rest_seconds": 0, "met_value": 3.3, "is_stretching": True, "video_url": "https://www.youtube.com/results?search_query=기초+요가+루틴"},
    {"plan_id": "home_dynamic_warmup", "name": "동적 웜업 루틴", "location": "home", "type": "time-based", "required_equipment": "", "target_parts": "full_body", "avoid_if_pain": "", "intensity": "medium", "minutes": 8, "sets": 1, "reps": 1, "target_rpe": 5, "rest_seconds": 0, "met_value": 4.0, "is_stretching": True, "video_url": "https://www.youtube.com/results?search_query=dynamic+warmup+routine"},
    {"plan_id": "gym_foam_roller_full", "name": "전신 폼롤러 근막이완", "location": "gym", "type": "time-based", "required_equipment": "foam_roller", "target_parts": "full_body", "avoid_if_pain": "", "intensity": "low", "minutes": 15, "sets": 1, "reps": 1, "target_rpe": 4, "rest_seconds": 0, "met_value": 2.5, "is_stretching": True, "video_url": "https://www.youtube.com/results?search_query=전신+폼롤러+마사지"},
    {"plan_id": "home_bedtime_stretch", "name": "취면 전 숙면 스트레칭", "location": "home", "type": "time-based", "required_equipment": "", "target_parts": "full_body", "avoid_if_pain": "", "intensity": "low", "minutes": 10, "sets": 1, "reps": 1, "target_rpe": 2, "rest_seconds": 0, "met_value": 1.5, "is_stretching": True, "video_url": "https://www.youtube.com/results?search_query=자기전+스트레칭"}
]

def seed_data():
    db: Session = SessionLocal()
    try:
        # Clear existing data to avoid conflicts during expansion
        # (Optional: Only if you want a clean state)
        # db.query(ExercisePlan).delete()
        
        for ex_data in SEED_EXERCISES:
            existing = db.query(ExercisePlan).filter(ExercisePlan.plan_id == ex_data["plan_id"]).first()
            if existing:
                for key, value in ex_data.items():
                    setattr(existing, key, value)
            else:
                new_plan = ExercisePlan(**ex_data)
                db.add(new_plan)
        
        db.commit()
        print(f"Successfully seeded {len(SEED_EXERCISES)} exercises into the database.")
    except Exception as e:
        print(f"Error during seeding: {e}")
        db.rollback()
    finally:
        db.close()

if __name__ == "__main__":
    seed_data()
